# Generated by Django 4.2.9 on 2024-10-24 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltraDCAEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('engine_name', models.CharField(default='', max_length=256)),
                ('order_number', models.PositiveIntegerField(default=0)),
                ('next_engine_start_order', models.PositiveIntegerField(default=None, help_text='after_how_many_orders_of_current_engine_next_engine_start', null=True)),
                ('next_engine_start_condition', models.FloatField(default=None, help_text='after_how_much_falls_of_current_engine_next_engine_start', null=True)),
                ('fall_order_engine_condition', models.FloatField(default=None, help_text='after_how_much_falls_of_latest_order_in_current_engine_fall_order_starts', null=True)),
                ('fall_order_market_condition', models.FloatField(default=None, help_text='after_how_much_falls_of_price_from_marketLine_fall_order_starts', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UltraGridSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('market_type', models.IntegerField(choices=[(0, 'Futures'), (1, 'Spot')], default=0)),
                ('market_strategy', models.IntegerField(choices=[(0, 'Isolated'), (1, 'Cross')], default=0)),
                ('system_name', models.CharField(max_length=256, unique=True)),
                ('system_fund_rate', models.FloatField(default=0)),
                ('system_balance', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(choices=[(0, 'در حال اجرا'), (1, 'مشغول'), (2, 'متوقف')], default=0)),
                ('buy_is_enabled', models.BooleanField(default=True)),
                ('sell_is_enabled', models.BooleanField(default=True)),
                ('err_msg', models.TextField()),
                ('order_number', models.PositiveIntegerField(default=0)),
                ('part_number', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UltraGridPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('part_name', models.CharField(default='', max_length=256)),
                ('start_order_number', models.PositiveIntegerField(default=0)),
                ('end_order_number', models.PositiveIntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('part_fund_rate', models.FloatField(default=0)),
                ('next_order_condition', models.FloatField(default=0, help_text='after_how_much_falls_of_current_order_next_order_start')),
                ('take_profit_condition', models.FloatField(default=0, help_text='after_how_much_jump_order_close')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ultragridsystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UltraGridOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('order_fund_rate', models.FloatField()),
                ('order_status', models.IntegerField(choices=[(0, 'Failed'), (1, 'Pending'), (2, 'Processing'), (3, 'Success')], default=1)),
                ('tp_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sl_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('err_msg', models.TextField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ultragridpart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UltraGridExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('iteration', models.CharField(max_length=128)),
                ('type', models.IntegerField(choices=[(0, 'Ordinary'), (1, 'Tp'), (2, 'Sl')], default=0)),
                ('orderId', models.CharField(max_length=128)),
                ('base_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quote_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('line_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('order_type', models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell')], default=0)),
                ('place_type', models.IntegerField(choices=[(0, 'Limit'), (1, 'Market')], default=1)),
                ('order_details', models.JSONField(default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ultragridorder')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ultragridpart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UltraDCASystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('market_type', models.IntegerField(choices=[(0, 'Futures'), (1, 'Spot')], default=0)),
                ('market_strategy', models.IntegerField(choices=[(0, 'Isolated'), (1, 'Cross')], default=0)),
                ('system_name', models.CharField(max_length=256, unique=True)),
                ('system_fund_rate', models.FloatField(default=0)),
                ('system_balance', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(choices=[(0, 'در حال اجرا'), (1, 'مشغول'), (2, 'متوقف')], default=0)),
                ('buy_is_enabled', models.BooleanField(default=True)),
                ('sell_is_enabled', models.BooleanField(default=True)),
                ('err_msg', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('engine_number', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UltraDCAOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('order_fund_rate', models.FloatField()),
                ('order_status', models.IntegerField(choices=[(0, 'Failed'), (1, 'Pending'), (2, 'Processing'), (3, 'Success')], default=1)),
                ('tp_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sl_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('err_msg', models.TextField()),
                ('order_take_profit', models.FloatField(default=0)),
                ('order_name', models.CharField(default='', max_length=256)),
                ('next_order_start_condition', models.FloatField(default=None, help_text='after_how_much_falls_of_current_order_next_order_start', null=True)),
                ('next_order_start_time', models.IntegerField(default=None, help_text='after_how_many_time_next_order_start', null=True)),
                ('jumped_order', models.BooleanField(default=False)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ultradcaengine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UltraDCAExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('iteration', models.CharField(max_length=128)),
                ('type', models.IntegerField(choices=[(0, 'Ordinary'), (1, 'Tp'), (2, 'Sl')], default=0)),
                ('orderId', models.CharField(max_length=128)),
                ('base_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quote_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('line_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('order_type', models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell')], default=0)),
                ('place_type', models.IntegerField(choices=[(0, 'Limit'), (1, 'Market')], default=1)),
                ('order_details', models.JSONField(default=dict)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=8, help_text='my_line_price_after_average', max_digits=20, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ultradcaengine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ultradcaorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ultradcaengine',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ultradcasystem'),
        ),
    ]
