# Generated by Django 4.2.9 on 2024-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_currencies_user_email_verified_user_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_mode',
            field=models.IntegerField(choices=[(0, 'Hedge'), (1, 'Oneway')], default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='secret_key_hashed',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
